package httplog

var FullFormatterWithRequestAndResponseHeadersAndBody = ChainLogFormatter(DefaultLogFormatter, RequestHeaderLogFormatter, RequestBodyLogFormatter, ResponseHeaderLogFormatter, ResponseBodyLogFormatter)
